# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MysqlDb',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('host', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255, null=True, blank=True)),
                ('uptime', models.IntegerField(null=True, blank=True)),
                ('max_connections', models.CharField(max_length=255, null=True, blank=True)),
                ('threads_connected', models.IntegerField(null=True, blank=True)),
                ('threads_running', models.IntegerField(null=True, blank=True)),
                ('threads_created', models.IntegerField(null=True, blank=True)),
                ('threads_cached', models.IntegerField(null=True, blank=True)),
                ('threads_waited', models.IntegerField(null=True, blank=True)),
                ('conn_rate', models.CharField(max_length=255, null=True, blank=True)),
                ('conn_rate_level', models.CharField(max_length=255, null=True, blank=True)),
                ('qps', models.IntegerField(null=True, db_column=b'QPS', blank=True)),
                ('tps', models.IntegerField(null=True, db_column=b'TPS', blank=True)),
                ('bytes_received', models.IntegerField(null=True, blank=True)),
                ('bytes_send', models.IntegerField(null=True, blank=True)),
                ('mon_status', models.CharField(max_length=255)),
                ('rate_level', models.CharField(max_length=255)),
                ('chk_time', models.DateTimeField(null=True, blank=True)),
            ],
            options={
                'db_table': 'mysql_db',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MysqlDbHis',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('host', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255, null=True, blank=True)),
                ('uptime', models.IntegerField(null=True, blank=True)),
                ('max_connections', models.CharField(max_length=255, null=True, blank=True)),
                ('threads_connected', models.IntegerField(null=True, blank=True)),
                ('threads_running', models.IntegerField(null=True, blank=True)),
                ('threads_created', models.IntegerField(null=True, blank=True)),
                ('threads_cached', models.IntegerField(null=True, blank=True)),
                ('threads_waited', models.IntegerField(null=True, blank=True)),
                ('conn_rate', models.CharField(max_length=255, null=True, blank=True)),
                ('conn_rate_level', models.CharField(max_length=255, null=True, blank=True)),
                ('qps', models.IntegerField(null=True, db_column=b'QPS', blank=True)),
                ('tps', models.IntegerField(null=True, db_column=b'TPS', blank=True)),
                ('bytes_received', models.IntegerField(null=True, blank=True)),
                ('bytes_send', models.IntegerField(null=True, blank=True)),
                ('mon_status', models.CharField(max_length=255)),
                ('rate_level', models.CharField(max_length=255)),
                ('chk_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'mysql_db_his',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MysqlDbRate',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('host', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=255)),
                ('conn_decute', models.IntegerField()),
                ('cpu_decute', models.IntegerField()),
                ('mem_decute', models.IntegerField()),
                ('disk_decute', models.IntegerField()),
                ('db_rate', models.IntegerField()),
                ('db_rate_level', models.CharField(max_length=255)),
                ('db_rate_color', models.CharField(max_length=255)),
                ('db_rate_reason', models.CharField(max_length=255)),
                ('rate_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'mysql_db_rate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MysqlDbRateHis',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('host', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=255)),
                ('conn_decute', models.IntegerField()),
                ('cpu_decute', models.IntegerField()),
                ('mem_decute', models.IntegerField()),
                ('disk_decute', models.IntegerField()),
                ('db_rate', models.IntegerField()),
                ('db_rate_level', models.CharField(max_length=255)),
                ('db_rate_color', models.CharField(max_length=255)),
                ('db_rate_reason', models.CharField(max_length=255)),
                ('rate_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'mysql_db_rate_his',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MysqlRepl',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tags', models.CharField(max_length=255)),
                ('server_id', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=255)),
                ('is_master', models.CharField(max_length=255, null=True, blank=True)),
                ('is_slave', models.CharField(max_length=255, null=True, blank=True)),
                ('mysql_role', models.CharField(max_length=255, null=True, blank=True)),
                ('read_only', models.CharField(max_length=255, null=True, blank=True)),
                ('master_server', models.CharField(max_length=255, null=True, blank=True)),
                ('master_port', models.CharField(max_length=255, null=True, blank=True)),
                ('slave_io_run', models.CharField(max_length=255, null=True, blank=True)),
                ('slave_io_rate', models.CharField(max_length=255, null=True, blank=True)),
                ('slave_sql_run', models.CharField(max_length=255, null=True, blank=True)),
                ('slave_sql_rate', models.CharField(max_length=255, null=True, blank=True)),
                ('delay', models.CharField(max_length=255, null=True, blank=True)),
                ('delay_rate', models.CharField(max_length=255, null=True, blank=True)),
                ('current_binlog_file', models.CharField(max_length=255, null=True, blank=True)),
                ('current_binlog_pos', models.CharField(max_length=255, null=True, blank=True)),
                ('master_binlog_file', models.CharField(max_length=255, null=True, blank=True)),
                ('master_binlog_pos', models.CharField(max_length=255, null=True, blank=True)),
                ('master_binlog_space', models.CharField(max_length=255, null=True, blank=True)),
                ('chk_time', models.DateTimeField(null=True, blank=True)),
            ],
            options={
                'db_table': 'mysql_repl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MysqlReplHis',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tags', models.CharField(max_length=255)),
                ('server_id', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=255)),
                ('is_master', models.CharField(max_length=255, null=True, blank=True)),
                ('is_slave', models.CharField(max_length=255, null=True, blank=True)),
                ('mysql_role', models.CharField(max_length=255, null=True, blank=True)),
                ('read_only', models.CharField(max_length=255, null=True, blank=True)),
                ('master_server', models.CharField(max_length=255, null=True, blank=True)),
                ('master_port', models.CharField(max_length=255, null=True, blank=True)),
                ('slave_io_run', models.CharField(max_length=255, null=True, blank=True)),
                ('slave_io_rate', models.CharField(max_length=255, null=True, blank=True)),
                ('slave_sql_run', models.CharField(max_length=255, null=True, blank=True)),
                ('slave_sql_rate', models.CharField(max_length=255, null=True, blank=True)),
                ('delay', models.CharField(max_length=255, null=True, blank=True)),
                ('delay_rate', models.CharField(max_length=255, null=True, blank=True)),
                ('current_binlog_file', models.CharField(max_length=255, null=True, blank=True)),
                ('current_binlog_pos', models.CharField(max_length=255, null=True, blank=True)),
                ('master_binlog_file', models.CharField(max_length=255, null=True, blank=True)),
                ('master_binlog_pos', models.CharField(max_length=255, null=True, blank=True)),
                ('master_binlog_space', models.CharField(max_length=255, null=True, blank=True)),
                ('chk_time', models.DateTimeField(null=True, blank=True)),
            ],
            options={
                'db_table': 'mysql_repl_his',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TabMysqlServers',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tags', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('user_os', models.CharField(max_length=255)),
                ('password_os', models.CharField(max_length=255)),
                ('connect', models.CharField(max_length=255, null=True, blank=True)),
                ('connect_cn', models.CharField(max_length=255, null=True, blank=True)),
                ('repl', models.CharField(max_length=255, null=True, blank=True)),
                ('repl_cn', models.CharField(max_length=255, null=True, blank=True)),
                ('conn', models.CharField(max_length=255, null=True, blank=True)),
                ('conn_cn', models.CharField(max_length=255, null=True, blank=True)),
                ('err_info', models.CharField(max_length=255, null=True, blank=True)),
                ('err_info_cn', models.CharField(max_length=255, null=True, blank=True)),
            ],
            options={
                'db_table': 'tab_mysql_servers',
                'managed': False,
            },
        ),
    ]
