#! /usr/bin/python
# encoding:utf-8


from django.conf.urls import patterns, include, url

# 导入对应app的views文件
from frame import views as frame
from linux_mon import views as linux_mon
from oracle_mon import views as oracle_mon
from mysql_mon import views as mysql_mon
from redis_mon import views as redis_mon

from dba_blog import views as dba_blog

from login import views as login
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'time_test.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    (r'^linux_monitor/', linux_mon.linux_monitor),
    (r'^oracle_monitor/', oracle_mon.oracle_monitor),
    (r'^mysql_monitor/', mysql_mon.mysql_monitor),
    (r'^show_oracle/', oracle_mon.show_oracle),
    (r'^show_mysql/', mysql_mon.show_mysql),
    (r'^show_mysql_repl/', mysql_mon.show_mysql_repl),
    (r'^begin/', frame.show_all),
    (r'^my_check/', frame.my_check),
    (r'^check_err/', frame.check_err),
    (r'^checklist_del/', frame.checklist_del),
    (r'^show_linux_rate/', linux_mon.show_linux_rate),
    (r'^show_oracle_rate/', oracle_mon.show_oracle_rate),
    (r'^show_mysql_rate/', mysql_mon.show_mysql_rate),
    (r'^show_alarm/', frame.show_alarm),
    (r'^show_linux/$', linux_mon.show_linux),
    (r'^show_oracle_resource/', oracle_mon.show_oracle_resource),
    (r'^mon_servers/', frame.mon_servers),
    (r'^alarm_settings/', frame.alarm_setting),
    (r'^alarm_settings_edit$', frame.alarm_settings_edit),
    (r'^linux_servers_add/', frame.linux_servers_add),
    (r'^linux_servers_edit$', frame.linux_servers_edit),
    (r'^linux_servers_del$', frame.linux_servers_del),
    (r'^oracle_servers_add/', frame.oracle_servers_add),
    (r'^oracle_servers_edit$', frame.oracle_servers_edit),
    (r'^oracle_servers_del$', frame.oracle_servers_del),
    (r'^mysql_servers_add/', frame.mysql_servers_add),
    (r'^mysql_servers_edit$', frame.mysql_servers_edit),
    (r'^mysql_servers_del$', frame.mysql_servers_del),
    (r'^recorder/', frame.recorder),
    (r'^login/$', login.login_in),
    (r'^login$', login.login_in),
    (r'^recorder_add', frame.recorder_add),
    (r'^recorder_del$', frame.recorder_del),
    (r'^sys_setting/', frame.sys_setting),
    (r'^download$', frame.download),
    (r'^my_tools/', frame.my_tools),
    (r'^log_collect/', frame.log_collect),
    (r'^log_collects_edit$', frame.log_collects_edit),
    (r'^log_collects_del$', frame.log_collects_del),
    (r'^log_collects_add/', frame.log_collects_add),
    (r'^log_info$', frame.log_info),
    (r'^easy_start/', frame.easy_start),
    (r'^easy_starts_edit$', frame.easy_starts_edit),
    (r'^easy_starts_del$', frame.easy_starts_del),
    (r'^easy_starts_add/', frame.easy_starts_add),
    (r'^oracle_install/', frame.oracle_install),
    (r'^mysql_install/', frame.mysql_install),
    (r'^oracle_ctl/', oracle_mon.oracle_ctl),
    (r'^oracle_ctl$', oracle_mon.oracle_ctl),
    (r'^mysql_ctl/', mysql_mon.mysql_ctl),
    (r'^mysql_ctl$', mysql_mon.mysql_ctl),
    (r'^sql_exec/', oracle_mon.sql_exec),
    (r'^uploadFile/', oracle_mon.upload_file),
    (r'^oracle_lock_manage/', oracle_mon.oracle_lock_manage),
    (r'^oracle_session$', oracle_mon.oracle_session),
    (r'^oracle_process$', oracle_mon.oracle_process),
    (r'^oracle_undo$', oracle_mon.oracle_undo),
    (r'^oracle_temp$', oracle_mon.oracle_temp),
    (r'^oracle_active_session$', oracle_mon.oracle_active_session),
    (r'^oracle_waiting_session$', oracle_mon.oracle_waiting_session),
    (r'^oracle_pga', oracle_mon.oracle_pga),
    (r'^oracle_para', oracle_mon.oracle_para),
    (r'^kill_session$', oracle_mon.kill_session),
    (r'^oracle_switchover', oracle_mon.oracle_switchover),
    (r'^oracle_logminer', oracle_mon.oracle_logminer),
    (r'^oracle_audit', oracle_mon.oracle_audit),
    (r'^oracle_logs_add', oracle_mon.oracle_logs_add),
    (r'^oracle_top_sql/', oracle_mon.oracle_top_sql),
    (r'^oracle_sql$', oracle_mon.oracle_sql),
    (r'^show_sqltext/', oracle_mon.show_sqltext),
    (r'^oracle_backup/', oracle_mon.oracle_backup),
    (r'^oracle_rpt/', oracle_mon.oracle_rpt),
    (r'^oracle_rpt_ash/', oracle_mon.oracle_rpt_ash),
    (r'^oracle_perf/', oracle_mon.oracle_perf),
    (r'^show_report/', oracle_mon.show_report),
    (r'^delete_report/', oracle_mon.delete_report),
    url(r'^admin/', include(admin.site.urls)),
    (r'^oracle_tbs/', oracle_mon.oracle_tbs),
    (r'^oracle_profile/', oracle_mon.oracle_profile),
    (r'^oracle_grant/', oracle_mon.oracle_grant),
    (r'^my_task/', frame.my_task),
    (r'^my_scheduler/', frame.my_scheduler),
    (r'^scheduler_add/', frame.scheduler_add),
    (r'^scheduler_delete/', frame.scheduler_del),
    (r'^scheduler_edit/', frame.scheduler_edit),
    (r'^crontab_add/', frame.crontab_add),
    (r'^crontab_delete/', frame.crontab_del),
    (r'^crontab_edit/', frame.crontab_edit),
    (r'^scheduler_para/', frame.scheduler_para),
    (r'^show_mysql_res/', mysql_mon.show_mysql_res),
    (r'^mysql_big_table/', mysql_mon.mysql_big_table),
    (r'^mysql_slowquery/', mysql_mon.mysql_slowquery),
    (r'^show_sqltext_mysql/', frame.show_sqltext_mysql),
    (r'^show_linux_res/', linux_mon.show_linux_res),
    (r'^failure_add/', frame.failure_add),
    (r'^show_failure/', frame.show_failure),
    (r'^failure_delete/', frame.failure_del),
    (r'^failure_content/', frame.failure_content),
    (r'^failure_edit/', frame.failure_edit),
    (r'^test/', frame.jqtest),
    (r'^my_scripts/', frame.my_scripts),
    (r'^show_script_content/', frame.show_script_content),
    (r'^blog_index/', dba_blog.blog_index),
    (r'^article_detail/', dba_blog.article_detail),
    (r'^article_edit/', dba_blog.article_edit),
    (r'^article_archive/', dba_blog.article_archive),
    (r'^article_add/', dba_blog.article_add),
    (r'^article_delete/', dba_blog.article_delete),
    (r'^show_web_stats/', frame.show_web_stats),
    (r'^show_tcp_stats/', frame.show_tcp_stats),
    (r'^show_redis/', redis_mon.show_redis),
    (r'^redis_mon_conf_add/', redis_mon.redis_mon_conf_add),
    (r'^redis_mon_conf_edit$', redis_mon.redis_mon_conf_edit),
    (r'^redis_mon_conf_del$', redis_mon.redis_mon_conf_del),
    (r'^get_mysql_errorlog/', mysql_mon.get_mysql_errorlog),
    (r'^get_oracle_log/', oracle_mon.get_oracle_log),
                       )

handler404 = frame.page_not_found