# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-02-15 11:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xb6\xe9\x97\xb4')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98')),
                ('body', models.TextField(verbose_name=b'\xe6\xad\xa3\xe6\x96\x87')),
                ('pub_time', models.DateTimeField(blank=True, null=True, verbose_name=b'\xe5\x8f\x91\xe5\xb8\x83\xe6\x97\xb6\xe9\x97\xb4')),
                ('status', models.CharField(choices=[(b'd', b'\xe8\x8d\x89\xe7\xa8\xbf'), (b'p', b'\xe5\x8f\x91\xe8\xa1\xa8')], default=b'p', max_length=1, verbose_name=b'\xe6\x96\x87\xe7\xab\xa0\xe7\x8a\xb6\xe6\x80\x81')),
                ('comment_status', models.CharField(choices=[(b'o', b'\xe6\x89\x93\xe5\xbc\x80'), (b'c', b'\xe5\x85\xb3\xe9\x97\xad')], default=b'o', max_length=1, verbose_name=b'\xe8\xaf\x84\xe8\xae\xba\xe7\x8a\xb6\xe6\x80\x81')),
                ('type', models.CharField(choices=[(b'a', b'\xe6\x96\x87\xe7\xab\xa0'), (b'p', b'\xe9\xa1\xb5\xe9\x9d\xa2')], default=b'a', max_length=1, verbose_name=b'\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('views', models.PositiveIntegerField(default=0, verbose_name=b'\xe6\xb5\x8f\xe8\xa7\x88\xe9\x87\x8f')),
                ('article_order', models.IntegerField(default=0, verbose_name=b'\xe6\x8e\x92\xe5\xba\x8f,\xe6\x95\xb0\xe5\xad\x97\xe8\xb6\x8a\xe5\xa4\xa7\xe8\xb6\x8a\xe9\x9d\xa0\xe5\x89\x8d')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe4\xbd\x9c\xe8\x80\x85')),
            ],
            options={
                'ordering': ['-article_order', '-pub_time'],
                'get_latest_by': 'id',
                'verbose_name': '\u6587\u7ae0',
                'verbose_name_plural': '\u6587\u7ae0',
            },
        ),
        migrations.CreateModel(
            name='BlogSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(default=b'', max_length=200, verbose_name=b'\xe7\xbd\x91\xe7\xab\x99\xe5\x90\x8d\xe7\xa7\xb0')),
                ('site_description', models.TextField(default=b'', max_length=1000, verbose_name=b'\xe7\xbd\x91\xe7\xab\x99\xe6\x8f\x8f\xe8\xbf\xb0')),
                ('site_seo_description', models.TextField(default=b'', max_length=1000, verbose_name=b'\xe7\xbd\x91\xe7\xab\x99SEO\xe6\x8f\x8f\xe8\xbf\xb0')),
                ('site_keywords', models.TextField(default=b'', max_length=1000, verbose_name=b'\xe7\xbd\x91\xe7\xab\x99\xe5\x85\xb3\xe9\x94\xae\xe5\xad\x97')),
                ('article_sub_length', models.IntegerField(default=300, verbose_name=b'\xe6\x96\x87\xe7\xab\xa0\xe6\x91\x98\xe8\xa6\x81\xe9\x95\xbf\xe5\xba\xa6')),
                ('sidebar_article_count', models.IntegerField(default=10, verbose_name=b'\xe4\xbe\xa7\xe8\xbe\xb9\xe6\xa0\x8f\xe6\x96\x87\xe7\xab\xa0\xe6\x95\xb0\xe7\x9b\xae')),
                ('sidebar_comment_count', models.IntegerField(default=5, verbose_name=b'\xe4\xbe\xa7\xe8\xbe\xb9\xe6\xa0\x8f\xe8\xaf\x84\xe8\xae\xba\xe6\x95\xb0\xe7\x9b\xae')),
                ('show_google_adsense', models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe6\x98\xbe\xe7\xa4\xba\xe8\xb0\xb7\xe6\xad\x8c\xe5\xb9\xbf\xe5\x91\x8a')),
                ('google_adsense_codes', models.TextField(blank=True, default=b'', max_length=2000, null=True, verbose_name=b'\xe5\xb9\xbf\xe5\x91\x8a\xe5\x86\x85\xe5\xae\xb9')),
                ('open_site_comment', models.BooleanField(default=True, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe6\x89\x93\xe5\xbc\x80\xe7\xbd\x91\xe7\xab\x99\xe8\xaf\x84\xe8\xae\xba\xe5\x8a\x9f\xe8\x83\xbd')),
                ('beiancode', models.CharField(blank=True, default=b'', max_length=2000, null=True, verbose_name=b'\xe5\xa4\x87\xe6\xa1\x88\xe5\x8f\xb7')),
                ('analyticscode', models.TextField(default=b'', max_length=1000, verbose_name=b'\xe7\xbd\x91\xe7\xab\x99\xe7\xbb\x9f\xe8\xae\xa1\xe4\xbb\xa3\xe7\xa0\x81')),
                ('show_gongan_code', models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe6\x98\xbe\xe7\xa4\xba\xe5\x85\xac\xe5\xae\x89\xe5\xa4\x87\xe6\xa1\x88\xe5\x8f\xb7')),
                ('gongan_beiancode', models.TextField(blank=True, default=b'', max_length=2000, null=True, verbose_name=b'\xe5\x85\xac\xe5\xae\x89\xe5\xa4\x87\xe6\xa1\x88\xe5\x8f\xb7')),
                ('resource_path', models.CharField(default=b'/var/www/resource/', max_length=300, verbose_name=b'\xe9\x9d\x99\xe6\x80\x81\xe6\x96\x87\xe4\xbb\xb6\xe4\xbf\x9d\xe5\xad\x98\xe5\x9c\xb0\xe5\x9d\x80')),
            ],
            options={
                'verbose_name': '\u7f51\u7ad9\u914d\u7f6e',
                'verbose_name_plural': '\u7f51\u7ad9\u914d\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xb6\xe9\x97\xb4')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name=b'\xe5\x88\x86\xe7\xb1\xbb\xe5\x90\x8d')),
                ('slug', models.SlugField(blank=True, default=b'no-slug', max_length=60)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dba_blog.Category', verbose_name=b'\xe7\x88\xb6\xe7\xba\xa7\xe5\x88\x86\xe7\xb1\xbb')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u5206\u7c7b',
                'verbose_name_plural': '\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name=b'\xe9\x93\xbe\xe6\x8e\xa5\xe5\x90\x8d\xe7\xa7\xb0')),
                ('link', models.URLField(verbose_name=b'\xe9\x93\xbe\xe6\x8e\xa5\xe5\x9c\xb0\xe5\x9d\x80')),
                ('sequence', models.IntegerField(unique=True, verbose_name=b'\xe6\x8e\x92\xe5\xba\x8f')),
                ('is_enable', models.BooleanField(default=True, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe6\x98\xbe\xe7\xa4\xba')),
                ('show_type', models.CharField(choices=[(b'i', b'\xe9\xa6\x96\xe9\xa1\xb5'), (b'l', b'\xe5\x88\x97\xe8\xa1\xa8\xe9\xa1\xb5'), (b'p', b'\xe6\x96\x87\xe7\xab\xa0\xe9\xa1\xb5\xe9\x9d\xa2'), (b'a', b'\xe5\x85\xa8\xe7\xab\x99')], default=b'i', max_length=1, verbose_name=b'\xe6\x98\xbe\xe7\xa4\xba\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'ordering': ['sequence'],
                'verbose_name': '\u53cb\u60c5\u94fe\u63a5',
                'verbose_name_plural': '\u53cb\u60c5\u94fe\u63a5',
            },
        ),
        migrations.CreateModel(
            name='SideBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98')),
                ('content', models.TextField(verbose_name=b'\xe5\x86\x85\xe5\xae\xb9')),
                ('sequence', models.IntegerField(unique=True, verbose_name=b'\xe6\x8e\x92\xe5\xba\x8f')),
                ('is_enable', models.BooleanField(default=True, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe5\x90\xaf\xe7\x94\xa8')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'ordering': ['sequence'],
                'verbose_name': '\u4fa7\u8fb9\u680f',
                'verbose_name_plural': '\u4fa7\u8fb9\u680f',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xb6\xe9\x97\xb4')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name=b'\xe6\xa0\x87\xe7\xad\xbe\xe5\x90\x8d')),
                ('slug', models.SlugField(blank=True, default=b'no-slug', max_length=60)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u6807\u7b7e',
                'verbose_name_plural': '\u6807\u7b7e',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dba_blog.Category', verbose_name=b'\xe5\x88\x86\xe7\xb1\xbb'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='dba_blog.Tag', verbose_name=b'\xe6\xa0\x87\xe7\xad\xbe\xe9\x9b\x86\xe5\x90\x88'),
        ),
    ]
